name: Daily Robot Framework Tests

on:
  schedule:
    - cron: '30 3 * * *'   # 9:00 AM IST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # - name: Install Chrome and Chromedriver
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y chromium-browser chromium-chromedriver
      
      - name: Install Firefox & Geckodriver
        run: |
          sudo apt update
          sudo apt install -y firefox geckodriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: |
          mkdir -p results
          robot --outputdir results tests/

      - name: Upload Robot Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results
