name: Daily Robot Framework Tests

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '15 3 * * *'  # 8:45 AM IST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chrome-version: latest

      - name: Run Robot Framework tests
        run: |
          mkdir -p results
          robot --outputdir results tests/

      - name: Zip Robot results
        run: |
          zip -r results.zip results

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results.zip

      - name: Publish results to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./results
          publish_branch: gh-pages

      - name: Ensure summary file exists
        run: |
          mkdir -p results
          touch results/summary.txt

      - name: Send Test Result to Slack
        run: |
          SUMMARY=$(cat results/summary.txt | sed ':a;N;$!ba;s/\n/\\n/g')
          curl -X POST -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
               -H "Content-type: application/json" \
               -d "{\"channel\":\"C09ECPMQJ2C\",\"text\":\"$SUMMARY\"}" \
               https://slack.com/api/chat.postMessage
